// auth
export const COOKIE_LOADED = 'cookie_loaded'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAILURE = 'login_failure'
export const USER_INFO_LOADED = 'user_info'
export const USER_INFO_FAIL = 'user_info_fail'
export const REGISTER_SUCCESS = 'register_success'
export const REGISTER_FAILURE = 'register_failure'
export const LOGGED_OUT = 'logged_out'
export const FORGOT = 'forgot'
export const QUICKPLAY_SUCCESS = 'QUICKPLAY_SUCCESS'
export const QUICKPLAY_FAIL = 'QUICKPLAY_FAIL'
export const FBLOGIN = 'fblogin'
export const GGLOGIN = 'gglogin'
// game
export const SERVERS_LOADED = 'servers_loaded'
export const SERVERS_LOADED_FAIL = 'servers_loaded_fail'
export const CHARACTERS_LOADED = 'characters_loaded'
export const CHARACTERS_LOADED_FAIL = 'characters_loaded_fail'
export const GAME_RECHARGE_SUCCESS = 'GAME_RECHARGE_SUCCESS'
// purchase
export const PRODUCTS_LOADED = 'products_loaded'
export const PRODUCTS_LOADED_FAIL = 'products_loaded_fail'
export const ORDER_CREATED = 'ORDER_CREATED'
export const ORDER_CREATED_FAIL = 'ORDER_CREATED_FAIL'
export const ORDER_PAID = 'ORDER_PAID'
export const ORDER_PAID_FAIL = 'ORDER_PAID_FAIL'
export const ORDER_CALLBACK_SUCCESS = 'ORDER_CALLBACK_SUCCESS'
export const ORDER_CALLBACK_FAIL = 'ORDER_CALLBACK_FAIL'
// ui
export const LOADING_START = 'loading_start'
export const LOADING_END = 'loading_end'
export const BANNER_LOADED = 'BANNER_LOADED'
export const BANNER_LOADED_FAIL = 'BANNER_LOADED_FAIL'
export const LISTARTICLE_LOADED = 'LISTARTICLE_LOADED'
export const LISTARTICLE_LOADED_FAIL = 'LISTARTICLE_LOADED_FAIL'
export const ARTICLE_LOADED = 'ARTICLE_LOADED'
export const ARTICLE_LOADED_FAIL = 'ARTICLE_LOADED_FAIL'
export const RELEASE_META_LOADED = 'RELEASE_META_LOADED'
export const RELEASE_META_LOADED_FAIL = 'RELEASE_META_LOADED_FAIL'
// gate
export const BALANCE_INFO_LOADED = 'BALANCE_INFO_LOADED'
//export const BALANCE_INFO_LOADED_FAIL = 'BALANCE_INFO_LOADED_FAIL'
export const GATE_CONFIG_LOADED = 'GATE_CONFIG_LOADED'
export const GATE_CONFIG_LOADED_FAIL = 'GATE_CONFIG_LOADED_FAIL'
export const GATE_RULE_LOADED = 'GATE_RULE_LOADED'
export const GATE_RULE_LOADED_FAIL = 'GATE_RULE_LOADED_FAIL'
export const GATE_CARD_ROUTED = 'GATE_CARD_ROUTED'
export const GATE_CARD_ROUTED_FAIL = 'GATE_CARD_ROUTED_FAIL'
export const GATE_CARD_SUCCESS = 'GATE_CARD_SUCCESS'
export const GATE_CARD_FAIL = 'GATE_CARD_FAIL'
export const HISTORY_INFO_LOADED = 'HISTORY_INFO_LOADED'
// download
export const DOWNLOAD_EXPECT = 'DOWNLOAD_EXPECT'
export const DOWNLOAD_PROGESS = 'DOWNLOAD_PROGESS'
export const DOWNLOAD_DONE = 'DOWNLOAD_DONE'
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR'
